// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Provide hardcoded fallback url to ensure Next.js build workers don't fail when env is undefined
    url: process.env["DATABASE_URL"] || "file:d:/인터그리비티/saju/prisma/dev.db",
  },
});
